### ISSUE TITLE
Add check no duplicate accession IDs

### ISSUE THREAD

**Issue by jfy133** [SPAAM-workshop/AncientMetagenomeDirCheck#7]
Just thought, to check copy-paste errors, maybe a check whether a given `archive` and `archive_accession` is duplicated at any point?

**Comment by maxibor** [comment]
Need clarification: Should we check for duplicates within a single entry (between the accession numbers separated by `,`), or with all the entries in `tsv` ?

**Comment by jfy133** [comment]
Both. Idea would be to separate all rows with muliple IDs into new lines as well (to think about it in the current table format), then sort of do a 'summarise' counting how many times each ID is recorded. Anything >1 is flagged. 


i.e. 

```
ERS1234,ERS1235,
ERS12345
ERS1246
```

Gets converted to

```
ERS1234
ERS1235
ERS12345
ERS1246
```
